# Generated by Django 3.2.18 on 2023-04-03 18:40

import core.courses.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_courses', '0002_content_file_image_text_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=core.courses.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=core.courses.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
